name: Publish Library to Repository

on:
  release:
    types: [created]

jobs:
  publish-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
  
      - name: Build with Gradle
        run: ./gradlew assemble -Pversion=${{ github.event.release.tag_name }}
  
      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
